#encoding: utf-8

types_suite = """
xmmsv/t_xmmsv.c
xmmsv/t_xmmsv_serialization.c
xmmsv/t_coll.c
""".split()

server_suite = """
server/t_streamtype.c
server/t_config.c
""".split()

schema_suite = """
server/t_schema.c
""".split()

test_xmmstypes_src = """
runner/main.c
runner/valgrind.c
""".split() + types_suite

test_server_src = """
runner/main.c
runner/valgrind.c
../src/xmms/streamtype.c
../src/xmms/object.c
../src/xmms/config.c
../src/xmms/error.c
../src/lib/xmmsipc/msg.c
../src/lib/xmmsipc/transport.c
../src/lib/xmmssocket/socket_unix.c
../src/lib/xmmsipc/url.c
../src/lib/xmmssocket/socket_common.c
../src/xmms/compat/thread_name_prctl.c
../src/lib/xmmsipc/transport_unix.c
../src/lib/xmmsipc/socket_unix.c
../src/lib/xmmsipc/socket_tcp.c
../src/xmms/ipc.c
""".split() + server_suite

test_schema_src = """
runner/main.c
runner/valgrind.c
""".split() + schema_suite

schema_suite= ["server/t_schema.c"]

def configure(conf):
    conf.check_cc(header_name="CUnit/CUnit.h")
    conf.check_cc(lib="cunit", uselib_store="cunit")
    conf.check_cc(lib="ncurses", uselib_store="ncurses", mandatory=False)

    code = """
           static void T (void) __attribute__ ((constructor (220)));
           static void T (void) {};
    """
    conf.check_cc(fragment=code, type="c", msg="Checking for constructor attribute")

    conf.check_cfg(package='valgrind', uselib_store='valgrind', args='--cflags', mandatory=False)
    conf.env['CXXFLAGS'] += ['-I../_build_/default/src/xmms']


def build(bld):
    bld(features = 'c cprogram',
        target = 'test_xmmstypes',
        source = test_xmmstypes_src,
        includes = '. .. runner ../src ../src/include',
        use = 'xmmstypes', 
        uselib = 'cunit ncurses valgrind DISABLE_WRITESTRINGS',
        install_path = None
        )

    bld(features = 'c cprogram',
        target = 'test_server',
        source = test_server_src,
        includes = '. .. runner ../src ../src/includepriv ../src/include ../src/xmms',
        use = 'xmmstypes',
        uselib = 'cunit ncurses valgrind glib2 gthread2 DISABLE_WRITESTRINGS',
        install_path = None
        )

    bld(features = 'c cprogram',
        target = 'test_schema',
        source = test_schema_src,
        includes = '. .. runner ../src ../src/include',
        use = 'xmmstypes', 
        uselib = 'cunit ncurses valgrind DISABLE_WRITESTRINGS',
        install_path = None
        )

def options(o):
    pass
