from waftools.plugin import plugin

def plugin_configure(conf):
     if not conf.check_cc(lib="m", uselib_store="math"):
          return False
     return True

configure, build = plugin("ladspa", configure=plugin_configure, libs=["math"],
                          source=["ladspa.c", "ladspa_plugin.c"])
